"""
NetFusion AI Domain Models
Enterprise dataclass representations for explainable AI outputs, hypotheses,
risk metrics, confidence metadata, recommendations, MITRE reasoning, reports, and safety claims.
"""

import time
import uuid
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

from netfusion_workflow.enums import Priority, BusinessImpact, Likelihood
from .enums import (
    AnalysisCategory,
    ClaimType,
    ConfidenceLevel,
    RecommendationCategory,
    TacticalPhase,
)


@dataclass
class EvidenceReference:
    """Structured link to underlying evidence or canonical object."""
    evidence_id: str
    source_type: str  # e.g., "sysmon", "nmap", "tshark", "threat_intel", "timeline"
    summary: str
    relevance_score: float = 1.0
    timestamp: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "source_type": self.source_type,
            "summary": self.summary,
            "relevance_score": self.relevance_score,
            "timestamp": self.timestamp,
            "metadata": self.metadata,
        }


@dataclass
class Explanation:
    """Structured reasoning output explaining every AI conclusion."""
    evidence_references: List[EvidenceReference] = field(default_factory=list)
    reasoning_summary: str = ""
    confidence: ConfidenceLevel = ConfidenceLevel.MEDIUM
    assumptions: List[str] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)
    unknowns: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "evidence_references": [ref.to_dict() for ref in self.evidence_references],
            "reasoning_summary": self.reasoning_summary,
            "confidence": self.confidence.value if isinstance(self.confidence, ConfidenceLevel) else self.confidence,
            "assumptions": self.assumptions,
            "limitations": self.limitations,
            "unknowns": self.unknowns,
        }


@dataclass
class Claim:
    """Classified assertion generated by AI engines for safety verification."""
    statement: str
    claim_type: ClaimType = ClaimType.INFERENCE
    supporting_evidence: List[EvidenceReference] = field(default_factory=list)
    is_verified: bool = True
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "statement": self.statement,
            "claim_type": self.claim_type.value if isinstance(self.claim_type, ClaimType) else self.claim_type,
            "supporting_evidence": [e.to_dict() for e in self.supporting_evidence],
            "is_verified": self.is_verified,
            "notes": self.notes,
        }


@dataclass
class Hypothesis:
    """Analyst hypothesis generated by the HypothesisEngine."""
    hypothesis_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    description: str = ""
    supporting_evidence: List[EvidenceReference] = field(default_factory=list)
    contradicting_evidence: List[EvidenceReference] = field(default_factory=list)
    confidence: ConfidenceLevel = ConfidenceLevel.MEDIUM
    confidence_score: float = 0.5
    recommended_validation_steps: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "hypothesis_id": self.hypothesis_id,
            "title": self.title,
            "description": self.description,
            "supporting_evidence": [e.to_dict() for e in self.supporting_evidence],
            "contradicting_evidence": [e.to_dict() for e in self.contradicting_evidence],
            "confidence": self.confidence.value if isinstance(self.confidence, ConfidenceLevel) else self.confidence,
            "confidence_score": self.confidence_score,
            "recommended_validation_steps": self.recommended_validation_steps,
        }


@dataclass
class RecommendationItem:
    """Actionable remediation or investigation step."""
    recommendation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    category: RecommendationCategory = RecommendationCategory.FURTHER_INVESTIGATION
    description: str = ""
    priority: Priority = Priority.MEDIUM
    supporting_evidence: List[EvidenceReference] = field(default_factory=list)
    action_steps: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "recommendation_id": self.recommendation_id,
            "title": self.title,
            "category": self.category.value if isinstance(self.category, RecommendationCategory) else self.category,
            "description": self.description,
            "priority": self.priority.value if isinstance(self.priority, Priority) else self.priority,
            "supporting_evidence": [e.to_dict() for e in self.supporting_evidence],
            "action_steps": self.action_steps,
        }


@dataclass
class MITREInference:
    """ATT&CK TTP mapping inferred by MITREReasoner."""
    tactic: TacticalPhase = TacticalPhase.INITIAL_ACCESS
    technique_id: str = ""
    technique_name: str = ""
    sub_technique_id: Optional[str] = None
    sub_technique_name: Optional[str] = None
    kill_chain_progression_stage: int = 1  # 1 to 7
    confidence: ConfidenceLevel = ConfidenceLevel.MEDIUM
    confidence_score: float = 0.7
    supporting_evidence: List[EvidenceReference] = field(default_factory=list)
    description: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "tactic": self.tactic.value if isinstance(self.tactic, TacticalPhase) else self.tactic,
            "technique_id": self.technique_id,
            "technique_name": self.technique_name,
            "sub_technique_id": self.sub_technique_id,
            "sub_technique_name": self.sub_technique_name,
            "kill_chain_progression_stage": self.kill_chain_progression_stage,
            "confidence": self.confidence.value if isinstance(self.confidence, ConfidenceLevel) else self.confidence,
            "confidence_score": self.confidence_score,
            "supporting_evidence": [e.to_dict() for e in self.supporting_evidence],
            "description": self.description,
        }


@dataclass
class ConfidenceMetadata:
    """Multi-factor breakdown of overall AI confidence."""
    overall_score: float = 0.5  # 0.0 to 1.0
    confidence_level: ConfidenceLevel = ConfidenceLevel.MEDIUM
    evidence_quality: float = 0.5
    evidence_quantity: float = 0.5
    collector_reliability: float = 0.8
    threat_intel_confidence: float = 0.7
    correlation_strength: float = 0.5
    missing_information: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "overall_score": self.overall_score,
            "confidence_level": self.confidence_level.value if isinstance(self.confidence_level, ConfidenceLevel) else self.confidence_level,
            "evidence_quality": self.evidence_quality,
            "evidence_quantity": self.evidence_quantity,
            "collector_reliability": self.collector_reliability,
            "threat_intel_confidence": self.threat_intel_confidence,
            "correlation_strength": self.correlation_strength,
            "missing_information": self.missing_information,
        }


@dataclass
class RiskScore:
    """Multi-dimensional risk output calculated by RiskEngine."""
    risk_score: float = 0.0  # 0.0 to 10.0 scale
    business_impact: BusinessImpact = BusinessImpact.MEDIUM
    likelihood: Likelihood = Likelihood.MEDIUM
    confidence: ConfidenceLevel = ConfidenceLevel.MEDIUM
    priority: Priority = Priority.MEDIUM
    suggested_response: str = ""
    contributing_factors: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "risk_score": self.risk_score,
            "business_impact": self.business_impact.value if isinstance(self.business_impact, BusinessImpact) else self.business_impact,
            "likelihood": self.likelihood.value if isinstance(self.likelihood, Likelihood) else self.likelihood,
            "confidence": self.confidence.value if isinstance(self.confidence, ConfidenceLevel) else self.confidence,
            "priority": self.priority.value if isinstance(self.priority, Priority) else self.priority,
            "suggested_response": self.suggested_response,
            "contributing_factors": self.contributing_factors,
        }


@dataclass
class AIReport:
    """Comprehensive AI Investigation Report."""
    report_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    investigation_id: str = ""
    title: str = "AI Security Investigation Report"
    generated_at: float = field(default_factory=time.time)
    executive_summary: str = ""
    technical_summary: str = ""
    incident_narrative: str = ""
    timeline_narrative: str = ""
    evidence_narrative: str = ""
    mitre_findings: List[MITREInference] = field(default_factory=list)
    hypotheses: List[Hypothesis] = field(default_factory=list)
    risk_assessment: Optional[RiskScore] = None
    recommendations: Dict[str, List[RecommendationItem]] = field(default_factory=dict)
    appendices: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        rec_dict = {}
        for cat, items in self.recommendations.items():
            rec_dict[cat] = [i.to_dict() for i in items]
        return {
            "report_id": self.report_id,
            "investigation_id": self.investigation_id,
            "title": self.title,
            "generated_at": self.generated_at,
            "executive_summary": self.executive_summary,
            "technical_summary": self.technical_summary,
            "incident_narrative": self.incident_narrative,
            "timeline_narrative": self.timeline_narrative,
            "evidence_narrative": self.evidence_narrative,
            "mitre_findings": [m.to_dict() for m in self.mitre_findings],
            "hypotheses": [h.to_dict() for h in self.hypotheses],
            "risk_assessment": self.risk_assessment.to_dict() if self.risk_assessment else None,
            "recommendations": rec_dict,
            "appendices": self.appendices,
        }


@dataclass
class AnalysisResult:
    """Structured analytical response from AIAnalysisEngine."""
    analysis_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    investigation_id: str = ""
    category: AnalysisCategory = AnalysisCategory.INCIDENT_SUMMARY
    summary: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    facts: List[Claim] = field(default_factory=list)
    inferences: List[Claim] = field(default_factory=list)
    hypotheses: List[Hypothesis] = field(default_factory=list)
    recommendations: List[RecommendationItem] = field(default_factory=list)
    explanation: Optional[Explanation] = None
    confidence: Optional[ConfidenceMetadata] = None
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "analysis_id": self.analysis_id,
            "investigation_id": self.investigation_id,
            "category": self.category.value if isinstance(self.category, AnalysisCategory) else self.category,
            "summary": self.summary,
            "details": self.details,
            "facts": [f.to_dict() for f in self.facts],
            "inferences": [inf.to_dict() for inf in self.inferences],
            "hypotheses": [h.to_dict() for h in self.hypotheses],
            "recommendations": [r.to_dict() for r in self.recommendations],
            "explanation": self.explanation.to_dict() if self.explanation else None,
            "confidence": self.confidence.to_dict() if self.confidence else None,
            "created_at": self.created_at,
        }


@dataclass
class ConversationTurn:
    """Single interactive analyst-copilot turn in memory."""
    turn_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    prompt: str = ""
    response: str = ""
    provider_name: str = ""
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "turn_id": self.turn_id,
            "prompt": self.prompt,
            "response": self.response,
            "provider_name": self.provider_name,
            "timestamp": self.timestamp,
            "metadata": self.metadata,
        }
