"""
NetFusion AI Investigation Assistant Enums
Defines core enumeration types for providers, analytical categories, prompt types,
mitre tactics, risk ratings, confidence levels, claim classifications, and recommendations.
"""

from enum import Enum


class AIProviderType(str, Enum):
    """Supported AI Model / Provider adapters."""
    OPENAI = "openai"
    AZURE_OPENAI = "azure_openai"
    ANTHROPIC = "anthropic"
    GEMINI = "gemini"
    GROQ = "groq"
    OLLAMA = "ollama"
    MOCK = "mock"


class AnalysisCategory(str, Enum):
    """Categories of AI analysis generated by the AIAnalysisEngine."""
    INCIDENT_SUMMARY = "incident_summary"
    TECHNICAL_SUMMARY = "technical_summary"
    EVIDENCE_CORRELATION = "evidence_correlation"
    TIMELINE_ANALYSIS = "timeline_analysis"
    IOC_CORRELATION = "ioc_correlation"
    THREAT_ACTOR_ANALYSIS = "threat_actor_analysis"
    CAMPAIGN_ANALYSIS = "campaign_analysis"
    MALWARE_ASSESSMENT = "malware_assessment"
    ROOT_CAUSE = "root_cause"
    RECOMMENDATIONS = "recommendations"
    EXECUTIVE_BRIEF = "executive_brief"
    THREAT_HUNTING = "threat_hunting"
    FALSE_POSITIVE_REVIEW = "false_positive_review"
    CONTAINMENT_ADVICE = "containment_advice"


class PromptTemplateType(str, Enum):
    """Supported prompt templates in PromptBuilder."""
    INCIDENT_SUMMARY = "incident_summary"
    THREAT_HUNTING = "threat_hunting"
    IOC_ANALYSIS = "ioc_analysis"
    MITRE_ANALYSIS = "mitre_analysis"
    MALWARE_ANALYSIS = "malware_analysis"
    EXECUTIVE_REPORT = "executive_report"
    TECHNICAL_REPORT = "technical_report"
    NEXT_INVESTIGATION_STEPS = "next_investigation_steps"
    ROOT_CAUSE_ANALYSIS = "root_cause_analysis"
    FALSE_POSITIVE_REVIEW = "false_positive_review"
    CONTAINMENT_ADVICE = "containment_advice"


class RecommendationCategory(str, Enum):
    """Categorization for security recommendations."""
    CONTAINMENT = "containment"
    ERADICATION = "eradication"
    RECOVERY = "recovery"
    MONITORING = "monitoring"
    FURTHER_INVESTIGATION = "further_investigation"
    HARDENING = "hardening"


class TacticalPhase(str, Enum):
    """MITRE ATT&CK Enterprise Tactical Phases."""
    RECONNAISSANCE = "Reconnaissance"
    RESOURCE_DEVELOPMENT = "Resource Development"
    INITIAL_ACCESS = "Initial Access"
    EXECUTION = "Execution"
    PERSISTENCE = "Persistence"
    PRIVILEGE_ESCALATION = "Privilege Escalation"
    DEFENSE_EVASION = "Defense Evasion"
    CREDENTIAL_ACCESS = "Credential Access"
    DISCOVERY = "Discovery"
    LATERAL_MOVEMENT = "Lateral Movement"
    COLLECTION = "Collection"
    COMMAND_AND_CONTROL = "Command and Control"
    EXFILTRATION = "Exfiltration"
    IMPACT = "Impact"


class ConfidenceLevel(str, Enum):
    """Structured confidence scale."""
    VERY_LOW = "very_low"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"


class ClaimType(str, Enum):
    """Safety classification for AI assertions."""
    FACT = "fact"
    INFERENCE = "inference"
    HYPOTHESIS = "hypothesis"
    RECOMMENDATION = "recommendation"
