"""
AI Copilot, Conversation, Session Memory, & Context Window API package.
"""

from api.ai.copilot_router import (
    copilot_router,
    _reset_store as _reset_copilot_store,
    _COPILOT_STORE,
    find_session,
    sort_sessions,
    filter_sessions,
    paginate_sessions,
    append_chat_message,
    get_chat_history,
    clear_chat_history,
    build_chat_summary,
)
from api.ai.copilot_models import (
    CreateCopilotSessionRequest,
    UpdateCopilotSessionRequest,
    CopilotChatRequest,
    CopilotChatResponse,
    CopilotSessionResponse,
    CopilotSessionListResponse,
    CopilotStatisticsResponse,
    CopilotSearchResponse,
    BulkCreateCopilotSessionsRequest,
    BulkUpdateCopilotSessionsRequest,
    BulkDeleteCopilotSessionsRequest,
    BulkOperationResult as BulkCopilotOperationResult,
)

from api.ai.conversation_router import (
    conversation_router,
    _reset_store as _reset_conversation_store,
    _CONVERSATION_STORE,
    find_conversation,
    sort_conversations,
    filter_conversations,
    paginate_conversations,
    append_message,
    update_message,
    delete_message,
    find_message,
    search_messages,
    build_conversation_summary,
)
from api.ai.conversation_models import (
    CreateConversationRequest,
    UpdateConversationRequest,
    ConversationMessageRequest,
    ConversationMessageResponse,
    ConversationResponse,
    ConversationListResponse,
    ConversationStatisticsResponse,
    ConversationSearchResponse,
    BulkCreateConversationsRequest,
    BulkUpdateConversationsRequest,
    BulkDeleteConversationsRequest,
    BulkOperationResult as BulkConversationOperationResult,
    UpdateMessageRequest,
)

from api.ai.session_memory_router import (
    session_memory_router,
    _reset_store as _reset_memory_store,
    _MEMORY_STORE,
    find_memory,
    sort_memory,
    filter_memory,
    paginate_memory,
    append_memory_entry,
    update_memory_entry,
    delete_memory_entry,
    find_memory_entry,
    search_memory_entries,
    build_memory_summary,
)
from api.ai.session_memory_models import (
    CreateMemoryRequest,
    UpdateMemoryRequest,
    MemoryEntryRequest,
    MemoryEntryResponse,
    MemoryResponse,
    MemoryListResponse,
    MemoryStatisticsResponse,
    MemorySearchResponse,
    BulkCreateMemoryRequest,
    BulkUpdateMemoryRequest,
    BulkDeleteMemoryRequest,
    BulkOperationResult as BulkMemoryOperationResult,
    UpdateMemoryEntryRequest,
)

from api.ai.context_window_router import (
    context_window_router,
    _reset_store as _reset_context_store,
    _CONTEXT_STORE,
    find_context_window,
    sort_context_windows,
    filter_context_windows,
    paginate_context_windows,
    append_context_entry,
    update_context_entry,
    delete_context_entry,
    find_context_entry,
    search_context_entries,
    build_context_summary,
)
from api.ai.context_window_models import (
    CreateContextWindowRequest,
    UpdateContextWindowRequest,
    ContextWindowEntryRequest,
    ContextWindowEntryResponse,
    ContextWindowResponse,
    ContextWindowListResponse,
    ContextWindowStatisticsResponse,
    ContextWindowSearchResponse,
    BulkCreateContextWindowsRequest,
    BulkUpdateContextWindowsRequest,
    BulkDeleteContextWindowsRequest,
    BulkOperationResult as BulkContextOperationResult,
    UpdateContextWindowEntryRequest,
)

from api.ai.streaming_router import (
    streaming_router,
    _reset_store as _reset_streaming_store,
    _STREAM_STORE,
    find_stream,
    sort_streams,
    filter_streams,
    paginate_streams,
    append_stream_chunk,
    update_stream_chunk,
    delete_stream_chunk,
    find_stream_chunk,
    search_stream_chunks,
    build_stream_summary,
    calculate_stream_statistics,
    get_stream_status,
)
from api.ai.streaming_models import (
    CreateStreamRequest,
    UpdateStreamRequest,
    StreamChunkRequest,
    StreamChunkResponse,
    StreamResponse,
    StreamListResponse,
    StreamStatisticsResponse,
    StreamStatusResponse,
    StreamSummaryResponse,
    BulkCreateStreamsRequest,
    BulkUpdateStreamsRequest,
    BulkDeleteStreamsRequest,
    BulkOperationResult as BulkStreamOperationResult,
)

__all__ = [
    "copilot_router",
    "find_session",
    "sort_sessions",
    "filter_sessions",
    "paginate_sessions",
    "append_chat_message",
    "get_chat_history",
    "clear_chat_history",
    "build_chat_summary",
    "CreateCopilotSessionRequest",
    "UpdateCopilotSessionRequest",
    "CopilotChatRequest",
    "CopilotChatResponse",
    "CopilotSessionResponse",
    "CopilotSessionListResponse",
    "CopilotStatisticsResponse",
    "CopilotSearchResponse",
    "BulkCreateCopilotSessionsRequest",
    "BulkUpdateCopilotSessionsRequest",
    "BulkDeleteCopilotSessionsRequest",
    "BulkCopilotOperationResult",
    
    "conversation_router",
    "find_conversation",
    "sort_conversations",
    "filter_conversations",
    "paginate_conversations",
    "append_message",
    "update_message",
    "delete_message",
    "find_message",
    "search_messages",
    "build_conversation_summary",
    "CreateConversationRequest",
    "UpdateConversationRequest",
    "ConversationMessageRequest",
    "ConversationMessageResponse",
    "ConversationResponse",
    "ConversationListResponse",
    "ConversationStatisticsResponse",
    "ConversationSearchResponse",
    "BulkCreateConversationsRequest",
    "BulkUpdateConversationsRequest",
    "BulkDeleteConversationsRequest",
    "BulkConversationOperationResult",
    "UpdateMessageRequest",

    "session_memory_router",
    "find_memory",
    "sort_memory",
    "filter_memory",
    "paginate_memory",
    "append_memory_entry",
    "update_memory_entry",
    "delete_memory_entry",
    "find_memory_entry",
    "search_memory_entries",
    "build_memory_summary",
    "CreateMemoryRequest",
    "UpdateMemoryRequest",
    "MemoryEntryRequest",
    "MemoryEntryResponse",
    "MemoryResponse",
    "MemoryListResponse",
    "MemoryStatisticsResponse",
    "MemorySearchResponse",
    "BulkCreateMemoryRequest",
    "BulkUpdateMemoryRequest",
    "BulkDeleteMemoryRequest",
    "BulkMemoryOperationResult",
    "UpdateMemoryEntryRequest",

    "context_window_router",
    "find_context_window",
    "sort_context_windows",
    "filter_context_windows",
    "paginate_context_windows",
    "append_context_entry",
    "update_context_entry",
    "delete_context_entry",
    "find_context_entry",
    "search_context_entries",
    "build_context_summary",
    "CreateContextWindowRequest",
    "UpdateContextWindowRequest",
    "ContextWindowEntryRequest",
    "ContextWindowEntryResponse",
    "ContextWindowResponse",
    "ContextWindowListResponse",
    "ContextWindowStatisticsResponse",
    "ContextWindowSearchResponse",
    "BulkCreateContextWindowsRequest",
    "BulkUpdateContextWindowsRequest",
    "BulkDeleteContextWindowsRequest",
    "BulkContextOperationResult",
    "UpdateContextWindowEntryRequest",

    "streaming_router",
    "_reset_streaming_store",
    "_STREAM_STORE",
    "find_stream",
    "sort_streams",
    "filter_streams",
    "paginate_streams",
    "append_stream_chunk",
    "update_stream_chunk",
    "delete_stream_chunk",
    "find_stream_chunk",
    "search_stream_chunks",
    "build_stream_summary",
    "calculate_stream_statistics",
    "get_stream_status",
    "CreateStreamRequest",
    "UpdateStreamRequest",
    "StreamChunkRequest",
    "StreamChunkResponse",
    "StreamResponse",
    "StreamListResponse",
    "StreamStatisticsResponse",
    "StreamStatusResponse",
    "StreamSummaryResponse",
    "BulkCreateStreamsRequest",
    "BulkUpdateStreamsRequest",
    "BulkDeleteStreamsRequest",
    "BulkStreamOperationResult",
]
