"""
NetFusion IL-9 — AI Threat Reasoning Engine (ATRE)
===================================================
Evidence-driven multi-hop reasoning over the Unified Threat Knowledge Graph (UTKG)
and Canonical Intelligence Identity Layer (CIIL).
"""

from netfusion_ai.reasoning.api import router, get_atre_service, set_atre_service
from netfusion_ai.reasoning.attack_chain import AttackChainEngine
from netfusion_ai.reasoning.confidence import ConfidenceEngine
from netfusion_ai.reasoning.contradiction import ContradictionEngine
from netfusion_ai.reasoning.entity_resolution import ATREEntityResolver
from netfusion_ai.reasoning.events import (
    ReasoningEventPublisher,
    ReasoningStarted,
    ReasoningCompleted,
    HypothesisGenerated,
    EvidenceCollected,
    ConfidenceCalculated,
    AttackChainBuilt,
    RecommendationsGenerated,
    ReportGenerated,
)
from netfusion_ai.reasoning.explanation import ExplanationEngine
from netfusion_ai.reasoning.graph_reasoner import (
    GraphReasoner,
    EvidenceCollector,
    RelationshipRanker,
    ContextExpander,
    RiskPropagator,
    AttackChainBuilder,
    TimelineBuilder,
)
from netfusion_ai.reasoning.hypothesis import HypothesisEngine
from netfusion_ai.reasoning.memory import InvestigationMemoryEngine
from netfusion_ai.reasoning.models import (
    QuestionType,
    HypothesisStatus,
    ContradictionSeverity,
    ContradictionType,
    RecommendationCategory,
    RecommendationPriority,
    TimelineSource,
    ReportFormat,
    ReasoningRequest,
    CIILResolvedEntity,
    GraphEvidence,
    RelationshipRanking,
    AttackChainStage,
    AttackChain,
    Hypothesis,
    ConfidenceBreakdown,
    Contradiction,
    RiskAssessment,
    Recommendation,
    TimelineEvent,
    Timeline,
    MemoryItem,
    ReasoningPlan,
    ReasoningTraceStep,
    ExplanationResult,
    ReasoningResult,
)
from netfusion_ai.reasoning.orchestrator import ATREReasoningOrchestrator
from netfusion_ai.reasoning.planner import ReasoningPlanner
from netfusion_ai.reasoning.recommendations import ATRERecommendationEngine
from netfusion_ai.reasoning.risk import RiskEngine
from netfusion_ai.reasoning.service import ATREService
from netfusion_ai.reasoning.timeline import TimelineEngine

from netfusion_ai.reasoning.reasoning_trace import (
    ReasoningTraceEngine,
    SessionManager,
    DecisionRecorder,
    EvidenceRecorder,
    ConfidenceRecorder,
    GraphTraceRecorder,
    ExportEngine,
    VisualizationBuilder,
    ReasoningTrace,
    ReasoningSession,
    ReasoningStep,
    ReasoningDecision,
    ReasoningEvidence,
    ReasoningConfidence,
    ConfidenceContribution,
    ReasoningRule,
    ReasoningRecommendation,
    ReasoningExplanation,
    ErrorTrace,
    GraphTrace,
    TraceStarted,
    StageCompleted,
    DecisionRecorded,
    EvidenceRecorded,
    ConfidenceRecorded,
    RecommendationRecorded,
    TraceCompleted,
)

__all__ = [
    "ATREService",
    "ATREReasoningOrchestrator",
    "ReasoningPlanner",
    "ATREEntityResolver",
    "GraphReasoner",
    "EvidenceCollector",
    "RelationshipRanker",
    "ContextExpander",
    "RiskPropagator",
    "AttackChainBuilder",
    "TimelineBuilder",
    "HypothesisEngine",
    "ConfidenceEngine",
    "ContradictionEngine",
    "RiskEngine",
    "AttackChainEngine",
    "ATRERecommendationEngine",
    "TimelineEngine",
    "InvestigationMemoryEngine",
    "ExplanationEngine",
    "ReasoningTraceEngine",
    "SessionManager",
    "DecisionRecorder",
    "EvidenceRecorder",
    "ConfidenceRecorder",
    "GraphTraceRecorder",
    "ExportEngine",
    "VisualizationBuilder",
    "ReasoningTrace",
    "ReasoningSession",
    "ReasoningStep",
    "ReasoningDecision",
    "ReasoningEvidence",
    "ReasoningConfidence",
    "ConfidenceContribution",
    "ReasoningRule",
    "ReasoningRecommendation",
    "ReasoningExplanation",
    "ErrorTrace",
    "GraphTrace",
    "TraceStarted",
    "StageCompleted",
    "DecisionRecorded",
    "EvidenceRecorded",
    "ConfidenceRecorded",
    "RecommendationRecorded",
    "TraceCompleted",
    "QuestionType",
    "HypothesisStatus",
    "ContradictionSeverity",
    "ContradictionType",
    "RecommendationCategory",
    "RecommendationPriority",
    "TimelineSource",
    "ReportFormat",
    "ReasoningRequest",
    "CIILResolvedEntity",
    "GraphEvidence",
    "RelationshipRanking",
    "AttackChainStage",
    "AttackChain",
    "Hypothesis",
    "ConfidenceBreakdown",
    "Contradiction",
    "RiskAssessment",
    "Recommendation",
    "TimelineEvent",
    "Timeline",
    "MemoryItem",
    "ReasoningPlan",
    "ReasoningTraceStep",
    "ExplanationResult",
    "ReasoningResult",
    "ReasoningEventPublisher",
    "ReasoningStarted",
    "ReasoningCompleted",
    "HypothesisGenerated",
    "EvidenceCollected",
    "ConfidenceCalculated",
    "AttackChainBuilt",
    "RecommendationsGenerated",
    "ReportGenerated",
    "router",
    "get_atre_service",
    "set_atre_service",
]

